[package]
name = "german-string"
version = "0.1.0"
edition = "2021"

[dependencies]
static_assertions = "1.1"

[dev-dependencies]
criterion = { version = "0.5" }
pprof = { version = "0.14", features = ["flamegraph", "criterion"] }

[[bench]]
name = "scan_prefix"
harness = false
